// =====================================================================
// AUTO-GENERATED by scripts/upload-gallery.mjs — DO NOT EDIT BY HAND.
//
// Source: public/gallery/<parent>/<sub>/<project>/*.{jpg,png,webp,avif}
// Storage: Vercel Blob (public)
// Labels: scripts/gallery-labels.json
// Run:    npm run gallery:upload
//
// Currently empty — populated by the next gallery:upload run.
// =====================================================================

export type ParentCategoryId = 'businesses' | 'architecture' | 'carpentry';

export interface GalleryBusiness {
  id: string;
  name: string;
  location?: string;
  images: string[];
}

export interface GallerySubCategory {
  id: string;
  label: string;
  businesses: GalleryBusiness[];
}

export interface GalleryParentCategory {
  id: ParentCategoryId;
  label: string;
  subCategories: GallerySubCategory[];
}

export const projectsGalleryData: GalleryParentCategory[] = [];
